config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'pages#home'
get '/about', to: 'pages#about'
get 'signup', to: 'users#new'
post 'signup', to:'users#create'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
get '/search', to: 'searches#index'
get '/results', to: 'searches#results'

resources :users, only: [:show] do 
  resources :lists
end

resources :users
resources :searches, only: [:index, :show]
resources :shows, only: [:show, :destroy]
get '/show/add', to: 'shows#add'
end

app/models/api.rb
class Api < ApplicationRecord
    def get_anime_details(idnum)
        response = RestClient.get "https://kitsu.io/api/edge/anime/#{idnum}"
       
        json = JSON.parse(response)
        data = json["data"]
        hash = {}
        
        # byebug
        hash["id"] = data["id"]
        hash["name"] = data["attributes"]["titles"].first[1]
        hash["desc"] = data["attributes"]["description"]
        hash["title"] = data["attributes"]["titles"].first[1]
        hash["image"] = data["attributes"]["posterImage"]["large"]
        hash
     end

   #   def get_anime_collection
   #      response = RestClient.get "https://kitsu.io/api/edge/anime/"
   #      json = JSON.parse(response)
   #      @anime_collection = json["data"]
   #      @anime_collection
   #   end

     def search(string)
        string.gsub!(/\s/,'%20')
        response = RestClient.get "https://kitsu.io/api/edge/anime?filter[text]=#{string}&page[limit]=20"
        json = JSON.parse(response)
        json_data = json["data"]
        json_data
     end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    has_many :showlists
    has_many :shows, through: :showlists
    validates :name, presence: true, uniqueness: true
        
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :showlists
    has_many :lists, through: :showlists
    validates :name, presence: true
end

app/models/showlist.rb
class Showlist < ApplicationRecord
    belongs_to :show
    belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :lists
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :error, :warning, :info
    include ApplicationHelper
    
    def redirect_if_not_logged_in
        redirect_to signup_path if !logged_in?
    end

  
    def redirect_if_logged_in
        redirect_to user_path(current_user) if logged_in?
    end
    def logged_in?
        !!session[:user_id]
    end
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = current_user.lists
    end
    def show
        @list = List.find_by_id(params[:id])
    end

    def new
        @list = List.new(user_id: params[:user_id])
    end

    def create
        new_list = List.new(list_params)
        if new_list.save
            redirect_to user_lists_path, success: "List created!"
            return false
        else
            redirect_to new_user_list_path, error: new_list.errors.full_messages.to_sentence
        end
    end

    def edit
        @list = List.find_by_id(params[:id])
    end

    def update
        list = List.find_by_id(params[:id])
        list.update(list_params)
        redirect_to user_lists_path
    end

    def destroy
        List.find(params[:id]).destroy
        redirect_to user_lists_path
    end

    private
    
    def list_params
        params.require(:list).permit(:name, :desc, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def index
        
    end

    def results
        api_obj = Api.new
        @data = api_obj.search(params["search"])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new]
    
    
    def new
        @user = User.new
    end

    def create
        user = User.find_by_email(params[:user][:email])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user
        else
            redirect_to login_path, error: "Invalid credentials!"
        end
    end

    def destroy
        session.clear
        redirect_to '/'
    end

  end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    def show
        @animeid = params["id"]
        @details = Api.new.get_anime_details(@animeid)   
    end

    def add
        @details = Api.new.get_anime_details(params["show_id"])
        @new_show = Show.new(name: @details["name"], desc: @details["desc"], api_id: @details["id"], image: @details["image"])
        @list = List.find(params["list_id"])
        @list.shows.each do |show|
            if show.name == @new_show.name
                redirect_to show_path(id: params[:show_id]), error: "Anime already in list!"
                return false
            end
        end
        if @list.save
            @list.shows << @new_show
            redirect_to user_list_path(id: params["list_id"], user_id: current_user.id), success: "Anime already in list!"
        else
            redirect_to show_path(id: params[:show_id]), error: "Failed to add show!"
         end
    end

    def destroy
        show = Show.find(params["show_id"])
        list = List.find(params["list_id"])

        if show.destroy
            redirect_to user_list_path(id: params["list_id"], user_id: current_user.id)
        else
            # flash[:error] = "Deletion error!"
            redirect_to user_list_path(id: params["list_id"], user_id: current_user.id)
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new]
    before_action :redirect_if_not_logged_in, only: [:show, :index]
    
  

    def index
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.create(signup_params)
        if @user.id
            session[:user_id] = @user.id
            redirect_to user_lists_path(@user), success: "Account created!"
        else
            flash.now[:error] = @user.errors.full_messages.to_sentence
            render action: :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if current_user.update(signup_params)
            redirect_to user_path, success: "Updated!"
        else
            redirect_to user_edit_path(current_user)
        end
    end

    private

    def signup_params
        params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeListRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <%= render "/pages/navbar" %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<body class="lists-body">
    <div id="content">
        <h1 id="header-1"> Edit a list! </h1>

        <div class="formstyle">
            <%= form_with(model: @list, url: user_list_path) do |f| %>
                <%= f.hidden_field :user_id %>
                <%= f.label :name %>
                <%= f.text_field :name, id: "name", autocomplete: "off" %>
                <%= f.label "Description" %>
                <%= f.text_field :desc, id: "desc", autocomplete: "off" %>
                <%= f.submit "Submit", class: "list-submit" %>
            <% end %>
               <%= button_to "Back" %>
        </div>
    </div>
</body>

<script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>

app/views/lists/index.html.erb
<h1 id="h1lists">My lists</h1><br><br>
<body class="lists-body">

   <section id="list-listing">
      <p class="lists-pt">
        <% if !@lists.empty? %>
          <table id="list-data">
          <tr id="td-header">
            <th id="th-1">Name</th>
            <th id="th-2">Description</th>
          </tr>
          <% @lists.each do |c| %>
              <tr>
                <td><%= link_to c.name, user_list_path(id: c.id), id: "table-anchor" %></td>
                <td><%= c.desc %></td>
              </tr>
          <% end %>
          </table>
        <% else %>
          <p id="p1"><br><br><br><br> No list data!<br> </p>
        <% end %>
      </p>
    </section>
    <br><br><br><br>

<div id="container">
<%= link_to new_user_list_path, id: "button-anchor" do %>

    <div class="button1" id="button-3">
      <div id="circle"></div>
     <p id="button-text"> Create List</p>
    </div>
<% end %>
</div>

</body>

app/views/lists/new.html.erb
<body class="lists-body">
    <div id="content">
        <h1 id="header-1"> Create a list! </h1>

        <div class="formstyle">
            <%= form_with(model: @list, url: user_lists_path) do |f| %>
                <%= f.hidden_field :user_id %>
                <%= f.label :name %>
                <%= f.text_field :name, id: "name", autocomplete: "off" %>
                <%= f.label "Description" %>
                <%= f.text_field :desc, id: "desc", autocomplete: "off" %>
                <%= f.submit "Submit", class: "list-submit" %>
            <% end %>
               <%= button_to "Back" %>
        </div>
    </div>
</body>

<script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>

app/views/lists/show.html.erb
<body class="lists-body">

<div id="main-container">
<h1><%= @list.name%></h1>
  <% if !@list.shows.empty? %>
  <table id="list-data">
    <tr>
      <th id="th-name">Name</th>
      <th id="delete-col"></th>
    </tr>
  <% @list.shows.each do |c| %>
    <tr>
      <td><a class="arow" href="/shows/<%= c.api_id%>"><%= c.name %></a></td>
      <td><%= link_to "X", show_path(show_id: c.id, list_id: @list.id), method: "delete", class: "delete-button" %></td>
    </tr>   
  <% end %>
  </table>
<% else %>
    <br><br><br><br><br><br>
    <p id="p1"> No anime data! </p>
<% end %>


<br><br><br><br>    
      
<div id="container1">
  <br>
<% if !@list.shows.empty?%>
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="/lists/<%= @list.id %>/edit">Edit</a>
  </div>
  <% end %>
  <br>
  <div class="button" id="button-3">
    <div id="circle"></div>
        <%= button_to("Delete", user_list_path, method: "delete")  %>
       
  </div>
  <br>
<%= link_to edit_user_list_path do%>
   <div class="button" id="button-3">
      <div id="circle"></div>
      Edit
       
    </div>
<% end %>
<br>
<a>
   <div class="button" id="button-3">
      <div id="circle"></div>
        <form>
          <input type="button" value="Go back!" onclick="history.back()">
        </form>
    </div>
</a>
  <br>
  </div>
  </div>
  
</div>

app/views/pages/_errors.html.erb
 <br><br><br><br>

 <div class="flash-message"> 
    <% flash.each do |type, msg| %>
        <% if type == 'error' %>
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> <br><br>
                <strong>Error!</strong> <%= msg %>
            </div>
        <% elsif type == 'success'%>
            <div class="success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> <br><br>
                <strong>Success!</strong> <%= msg %>
            </div>
        <% end %>
    <% end %>
 </div>

app/views/pages/_navbar.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Open+Sans" rel="stylesheet">
</head>

<header id="layoutheader">
<a id="banner-anchor" href="/"><%= image_tag("doge2.jpeg", id: "doge", alt: "doge2.png", width: "5%") %></a> 
<h1 class="h-1"><a id="banner-anchor" href="/">Anime <span class="layoutspan">List</span></a></h1>
    <% if logged_in? %>
        <nav> 
            <ul id="layout-ul">
                <li> <%= link_to "Search", searches_path %></li>
                <li><a id="layout-a" href="/"> Home</a></li>
                <li><%= link_to "Lists", user_lists_path(current_user), id: "layout-a" %></li>
                 <li><a id="layout-a" href="#">About</a></li>  
                <li><%= link_to "Log out", logout_path, id: "layout-a" %></li>
            </ul>
        </nav>
    <% end %>
    <% if !logged_in? %>
        <nav> 
            <ul id="layout-ul">
                <li><a id="layout-a" href="/login"> Login</a></li>
                <li><a id="layout-a" href="/signup"> Sign Up</a></li>
                 <li><a id="layout-a" href="#">About</a></li>
            </ul>
        </nav>
    <% end %>
</header>


<%= render "pages/errors" %>

app/views/pages/home.html.erb
<%= stylesheet_link_tag "pages" %>

<body class="home-body">
   <%= image_tag("animelistlogo6.png", id: "logo") %>

  <ul class="bot_nav">
        <li id="l"><br>Contact me here!<p> <a href="mailto:michael.martinez2707@gmail.com">michael.martinez2707@gmail.com</a><br></p></li>
        <li id="l"><br>Github page<p><a href="https://github.com/lonelydomino/listlist" target="_blank">Github</a><br></p></li>
        <li id="l"><br>Follow <p><a href="https://www.twitch.tv/drmilomd" target="_blank">Twitch</a><br> </p></li>
      </ul>
</body>

app/views/searches/index.html.erb
<body class="searches-body">
    <div id="cover">
        <%= form_with(url: '/results', method: :get, class: "search-form") do |f|%>
                <div class="tb">
                    <div class="td">
                        <%= f.text_field :search, placeholder: "Search", required: "", autocomplete: "off" %>
                    </div>
                    <div class="td" id="s-cover">
                        <button type="submit">
                            <div id="s-circle"></div>
                            <span></span>
                        </button>
                    </div>
                </div>
        <% end %>
    </div>
</body>

app/views/searches/results.html.erb
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
</head>
<body class="results-body">
<ul class="tilesWrap">
<% if !@data.empty? %>
<br><br>
    <% @data.each do |d| %> 
        <li>
            <% @image = d["attributes"]["posterImage"]["small"] %>
			<% @title = d["attributes"]["canonicalTitle"] %> 
			<% @rating = d["attributes"]["averageRating"] %> 
			<% @episode_count = d["attributes"]["episodeCount"] %> 
			<% @id = d["id"] %> 
            <img class="a-img" src="<%= @image %>" alt="<%= @title %>_image">
			
            <br><br><br> 
            <h2><%= @title %>  </h2>
		    <h3><%= @title %>   </h3>
            <p>
			Rating: <%= @rating %> / 100 <br>
			Episode count: <%= @episode_count%> 
			</p> 
            <%= link_to show_path(@id), id: "results_anchor" do %>
                <%= button_to "Details" %>
            <% end %>
        
			
        </li>
    <% end %> 
</ul>
	<% else %>
	<div id="no-results">  No results found! </div>
		
	<% end %>


</body>

app/views/shows/show.html.erb
<div class="row">
    <div class="column" id="c1">
      <p><img src="<%= @details["image"] %>" alt="<%= @details["name"] %>_image"></p>
    </div> 
    <div class="column" id="c2">
        <h1><%= @details["title"] %> </h1>
        <p>
            <h4 id="title-h"><span id="title-h1-span">  <b> Description </b></span> <br><%= @details["desc"] %></h4>
        </p>
        <div id="row2">
            <h4>Add to list:
                    <div class="dropdown">
                        <button class="dropbtn">Lists </button>
                        <div class="dropdown-content">
                            <% current_user.lists.each do |list| %>
                                <%= link_to list.name, show_add_path(:list_id => list.id, :show_id => @details["id"] ) %>
                            <% end %>
                        </div>
                    </div> 
            </h4>
            <div class="button" id="button-3">
                <div id="circle"></div>
                    <form>
                        <input type="button" value="Go back!" onclick="history.back()">
                    </form>
            </div>
        </div>
    </div>
</div>
<br><br>
<script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>

app/views/users/new.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">


<body class="signup-body">
    <div class="testbox">
        <h1>Registration</h1>

        <%= form_for @user, html: {class: "signup-form", autocomplete: "off"} do |f| %>
        <hr><hr>
      
        <%= f.label :email, id: "icon" do%>
            <i class="icon-envelope "></i>
        <% end %>
        <%= f.email_field :email, placeholder: "Email", required: ""  %>  <br>

        <%= f.label :username, id: "icon" do%>
            <i class="icon-user "></i>
        <% end %>
        <%= f.text_field :username, placeholder: "Username", required: ""  %>  <br>

        <%= f.label :name, id: "icon" do%>
            <i class="icon-shield "></i>
        <% end %>
        <%= f.password_field :password, placeholder: "Password", required: "" %>
        <%= f.submit "Register", class: "button"  %>
        <% end %>

       
    </div>
</body>


<script>
var close = document.getElementsByClassName("closebtn");
var i;

for (i = 0; i < close.length; i++) {
  close[i].onclick = function(){
    var div = this.parentElement;
    div.style.opacity = "0";
    setTimeout(function(){ div.style.display = "none"; }, 600);
  }
}
</script>